Build: fix linking error
/home/circleci/project/src/server/game/Movement/MovementGenerators/RandomMovementGenerator.cpp:50:9: fatal error: use of undeclared identifier 'AddFlag'
        AddFlag(MOVEMENTGENERATOR_FLAG_TIMED_PAUSED);
        ^

(cherry picked from commit ec1a77bca20487f86765620485db9b13bb03aee8)